apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-score-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-score
  template:
    metadata:
      labels:
        app: student-score
    spec:
      containers:
      - name: student-score
        image: veera2605/student-score:latest
        ports:
        - containerPort: 5000